In [1]:
import pandas as pd

In [2]:
des = r"C:\Users\jamil\Desktop\Interpol KG Project\data\targets.simple.csv"
Interpol_data = pd.read_csv(des)

print("== Basic inforamtions about the Interpol data==")
print(f"Interpol Data shape is :{Interpol_data.shape}")

print("\n Showing the column's name for the dataset")
print(Interpol_data.columns.tolist())

== Basic inforamtions about the Interpol data==
Interpol Data shape is :(6561, 15)

 Showing the column's name for the dataset
['id', 'schema', 'name', 'aliases', 'birth_date', 'countries', 'addresses', 'identifiers', 'sanctions', 'phones', 'emails', 'dataset', 'first_seen', 'last_seen', 'last_change']

In [3]:
Interpol_data

,id,schema,name,aliases,birth_date,countries,addresses,identifiers,sanctions,phones,emails,dataset,first_seen,last_seen,last_change
0,NK-224TRezPqwzhQZ37exWxtX,Person,SANAVBARI NIKITENKO,NaN,1992-06-28,ru;tj,NaN,NaN,"""Red Notice - participation in the activity of...",NaN,NaN,INTERPOL Red Notices,2024-03-04T17:09:51,2025-05-23T18:28:10,2024-08-08T18:27:02
1,NK-22baaNEkbgBeZokNLmpaKd,Person,DZHAMBULAT GALIMOV,NaN,1989-01-05,ru,NaN,NaN,Red Notice - Participation in illegal armed fo...,NaN,NaN,INTERPOL Red Notices,2024-03-04T17:09:51,2025-05-23T18:28:10,2024-08-08T18:27:02
2,NK-282timUs47w9otBkgPN6hw,Person,KHAVA EFENDIEVA,NaN,1982-05-24,ru,NaN,NaN,Red Notice - Participation in illegal armed fo...,NaN,NaN,INTERPOL Red Notices,2024-03-04T17:09:51,2025-05-23T18:28:10,2024-08-08T18:27:02
3,NK-2Ld7pewCoLeyspMtVCMMMo,Person,JIAN XIA,NaN,1977-07-13,cn,NaN,NaN,"""Red Notice - 1) Murder\n2) Manslaughter\n3) A...",NaN,NaN,INTERPOL Red Notices,2024-03-04T17:09:51,2025-05-23T18:28:10,2024-08-08T18:27:02
4,NK-2VDD5G22HBksrjek2CoNJo,Person,GIENADIJ FAKTOROVICH,NaN,1970-06-12,il;ua,NaN,NaN,"""Red Notice - PARTICIPATION IN A CRIMINAL ORGA...",NaN,NaN,INTERPOL Red Notices,2024-03-04T17:09:51,2025-05-23T18:28:10,2024-08-08T18:27:02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6556,interpol-red-2025-6505,Person,JULIO ENRIQUE AMAYA TURCIOS,NaN,1993-03-20,NaN,NaN,NaN,Red Notice - FEMICIDIO,NaN,NaN,INTERPOL Red Notices,2025-01-31T00:27:15,2025-05-23T18:28:10,2025-01-31T00:27:15
6557,interpol-red-2025-6889,Person,GUILIANG TAN,NaN,2001-08-10,cn,NaN,NaN,Red Notice - Criminal act of trafficking in pe...,NaN,NaN,INTERPOL Red Notices,2025-01-30T18:27:03,2025-05-23T18:28:10,2025-01-30T18:27:03
6558,interpol-red-2025-6891,Person,CHEN GUOTENG,NaN,1971-04-24,cn,NaN,NaN,Red Notice - Criminal act of trafficking in pe...,NaN,NaN,INTERPOL Red Notices,2025-01-30T18:27:03,2025-05-23T18:28:10,2025-01-30T18:27:03
6559,interpol-red-2025-8298,Person,JODY JANILLE RHAMDAS,NaN,1985-02-28,bz,NaN,NaN,Red Notice - Attempted Murder,NaN,NaN,INTERPOL Red Notices,2025-02-05T18:27:04,2025-05-23T18:28:10,2025-02-05T18:27:04
6560,interpol-red-2025-9385,Person,MOHAMED GHARBI,NaN,1989-05-19,fr,NaN,NaN,Red Notice - VOL EN BANDE ORGANISEE AVEC ARME,NaN,NaN,INTERPOL Red Notices,2025-02-10T00:29:34,2025-05-23T18:28:10,2025-02-10T00:29:34

In [4]:
# Showing the first five rows for the dataset
print("\n === Showing the first five rows for the dataset ===") 
print(Interpol_data.head())

 === Showing the first five rows for the dataset ===
                          id  schema                  name aliases  \
0  NK-224TRezPqwzhQZ37exWxtX  Person   SANAVBARI NIKITENKO     NaN
1  NK-22baaNEkbgBeZokNLmpaKd  Person    DZHAMBULAT GALIMOV     NaN
2  NK-282timUs47w9otBkgPN6hw  Person       KHAVA EFENDIEVA     NaN
3  NK-2Ld7pewCoLeyspMtVCMMMo  Person              JIAN XIA     NaN
4  NK-2VDD5G22HBksrjek2CoNJo  Person  GIENADIJ FAKTOROVICH     NaN

   birth_date countries  addresses  identifiers  \
0  1992-06-28     ru;tj        NaN          NaN
1  1989-01-05        ru        NaN          NaN
2  1982-05-24        ru        NaN          NaN
3  1977-07-13        cn        NaN          NaN
4  1970-06-12     il;ua        NaN          NaN

                                           sanctions  phones  emails  \
0  "Red Notice - participation in the activity of...     NaN     NaN
1  Red Notice - Participation in illegal armed fo...     NaN     NaN
2  Red Notice - Participation in illegal armed fo...     NaN     NaN
3  "Red Notice - 1) Murder\n2) Manslaughter\n3) A...     NaN     NaN
4  "Red Notice - PARTICIPATION IN A CRIMINAL ORGA...     NaN     NaN

                dataset           first_seen            last_seen  \
0  INTERPOL Red Notices  2024-03-04T17:09:51  2025-05-23T18:28:10
1  INTERPOL Red Notices  2024-03-04T17:09:51  2025-05-23T18:28:10
2  INTERPOL Red Notices  2024-03-04T17:09:51  2025-05-23T18:28:10
3  INTERPOL Red Notices  2024-03-04T17:09:51  2025-05-23T18:28:10
4  INTERPOL Red Notices  2024-03-04T17:09:51  2025-05-23T18:28:10

           last_change
0  2024-08-08T18:27:02
1  2024-08-08T18:27:02
2  2024-08-08T18:27:02
3  2024-08-08T18:27:02
4  2024-08-08T18:27:02

In [5]:
# Data type and missing value checks
print("=== Interpol data information ===")
print(Interpol_data.info())

=== Interpol data information ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6561 entries, 0 to 6560
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           6561 non-null   object
 1   schema       6561 non-null   object
 2   name         6561 non-null   object
 3   aliases      2 non-null      object
 4   birth_date   6557 non-null   object
 5   countries    6506 non-null   object
 6   addresses    0 non-null      float64
 7   identifiers  0 non-null      float64
 8   sanctions    6557 non-null   object
 9   phones       0 non-null      float64
 10  emails       0 non-null      float64
 11  dataset      6561 non-null   object
 12  first_seen   6561 non-null   object
 13  last_seen    6561 non-null   object
 14  last_change  6561 non-null   object
dtypes: float64(4), object(11)
memory usage: 769.0+ KB
None

In [6]:
print("\nMissing value statistics:")
print(Interpol_data.isna().sum())

Missing value statistics:
id                0
schema            0
name              0
aliases        6559
birth_date        4
countries        55
addresses      6561
identifiers    6561
sanctions         4
phones         6561
emails         6561
dataset           0
first_seen        0
last_seen         0
last_change       0
dtype: int64

In [7]:
## Columns to Keep
columns_to_keep = [
    'id',          # unique person node
    'name',        # person name
    'aliases',     # other names
    'birth_date',  # temporal attribute
    'countries',   # nationality / wanted by
    'sanctions',   # type of crime
    'first_seen',  # timeline
    'last_seen',   # timeline
    'last_change'  # history / updates
]
Interpol_data = Interpol_data[columns_to_keep] 
Interpol_data

,id,name,aliases,birth_date,countries,sanctions,first_seen,last_seen,last_change
0,NK-224TRezPqwzhQZ37exWxtX,SANAVBARI NIKITENKO,NaN,1992-06-28,ru;tj,"""Red Notice - participation in the activity of...",2024-03-04T17:09:51,2025-05-23T18:28:10,2024-08-08T18:27:02
1,NK-22baaNEkbgBeZokNLmpaKd,DZHAMBULAT GALIMOV,NaN,1989-01-05,ru,Red Notice - Participation in illegal armed fo...,2024-03-04T17:09:51,2025-05-23T18:28:10,2024-08-08T18:27:02
2,NK-282timUs47w9otBkgPN6hw,KHAVA EFENDIEVA,NaN,1982-05-24,ru,Red Notice - Participation in illegal armed fo...,2024-03-04T17:09:51,2025-05-23T18:28:10,2024-08-08T18:27:02
3,NK-2Ld7pewCoLeyspMtVCMMMo,JIAN XIA,NaN,1977-07-13,cn,"""Red Notice - 1) Murder\n2) Manslaughter\n3) A...",2024-03-04T17:09:51,2025-05-23T18:28:10,2024-08-08T18:27:02
4,NK-2VDD5G22HBksrjek2CoNJo,GIENADIJ FAKTOROVICH,NaN,1970-06-12,il;ua,"""Red Notice - PARTICIPATION IN A CRIMINAL ORGA...",2024-03-04T17:09:51,2025-05-23T18:28:10,2024-08-08T18:27:02
...,...,...,...,...,...,...,...,...,...
6556,interpol-red-2025-6505,JULIO ENRIQUE AMAYA TURCIOS,NaN,1993-03-20,NaN,Red Notice - FEMICIDIO,2025-01-31T00:27:15,2025-05-23T18:28:10,2025-01-31T00:27:15
6557,interpol-red-2025-6889,GUILIANG TAN,NaN,2001-08-10,cn,Red Notice - Criminal act of trafficking in pe...,2025-01-30T18:27:03,2025-05-23T18:28:10,2025-01-30T18:27:03
6558,interpol-red-2025-6891,CHEN GUOTENG,NaN,1971-04-24,cn,Red Notice - Criminal act of trafficking in pe...,2025-01-30T18:27:03,2025-05-23T18:28:10,2025-01-30T18:27:03
6559,interpol-red-2025-8298,JODY JANILLE RHAMDAS,NaN,1985-02-28,bz,Red Notice - Attempted Murder,2025-02-05T18:27:04,2025-05-23T18:28:10,2025-02-05T18:27:04
6560,interpol-red-2025-9385,MOHAMED GHARBI,NaN,1989-05-19,fr,Red Notice - VOL EN BANDE ORGANISEE AVEC ARME,2025-02-10T00:29:34,2025-05-23T18:28:10,2025-02-10T00:29:34

In [8]:
print("=== Before Imputation ===")
print(Interpol_data.isnull().sum())

=== Before Imputation ===
id                0
name              0
aliases        6559
birth_date        4
countries        55
sanctions         4
first_seen        0
last_seen         0
last_change       0
dtype: int64

In [9]:
import pandas as pd

# For aliases - fill with empty list or string
Interpol_data['aliases'] = Interpol_data['aliases'].fillna('0')  # or .fillna([])

# For birth_date - keep null but create indicator
Interpol_data['birth_date_missing'] = Interpol_data['birth_date'].isna().astype(int)

# For countries - fill with 'Unknown'
Interpol_data['countries'] = Interpol_data['countries'].fillna('Unknown')

# For sanctions - verify then fill
Interpol_data['sanctions'] = Interpol_data['sanctions'].fillna('No')  # or verify first

# Alternative: Drop rows only if multiple critical fields are missing
df_cleaned = Interpol_data.dropna(subset=['birth_date', 'countries', 'sanctions'], 
                       thresh=2)  # keep if at least 2 of 3 are present

C:\Users\jamil\AppData\Local\Temp\ipykernel_18512\3556137900.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Interpol_data['aliases'] = Interpol_data['aliases'].fillna('0')  # or .fillna([])
C:\Users\jamil\AppData\Local\Temp\ipykernel_18512\3556137900.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Interpol_data['birth_date_missing'] = Interpol_data['birth_date'].isna().astype(int)
C:\Users\jamil\AppData\Local\Temp\ipykernel_18512\3556137900.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Interpol_data['countries'] = Interpol_data['countries'].fillna('Unknown')
C:\Users\jamil\AppData\Local\Temp\ipykernel_18512\3556137900.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Interpol_data['sanctions'] = Interpol_data['sanctions'].fillna('No')  # or verify first

In [10]:
print("=== After Imputation ===")
print(Interpol_data.isnull().sum())

=== After Imputation ===
id                    0
name                  0
aliases               0
birth_date            4
countries             0
sanctions             0
first_seen            0
last_seen             0
last_change           0
birth_date_missing    0
dtype: int64

In [11]:
Interpol_data.rename(columns=lambda x: x.strip(), inplace=True)  # Remove leading/trailing spaces from column names

C:\Users\jamil\AppData\Local\Temp\ipykernel_18512\1417774357.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Interpol_data.rename(columns=lambda x: x.strip(), inplace=True)  # Remove leading/trailing spaces from column names

In [12]:
Interpol_data

,id,name,aliases,birth_date,countries,sanctions,first_seen,last_seen,last_change,birth_date_missing
0,NK-224TRezPqwzhQZ37exWxtX,SANAVBARI NIKITENKO,0,1992-06-28,ru;tj,"""Red Notice - participation in the activity of...",2024-03-04T17:09:51,2025-05-23T18:28:10,2024-08-08T18:27:02,0
1,NK-22baaNEkbgBeZokNLmpaKd,DZHAMBULAT GALIMOV,0,1989-01-05,ru,Red Notice - Participation in illegal armed fo...,2024-03-04T17:09:51,2025-05-23T18:28:10,2024-08-08T18:27:02,0
2,NK-282timUs47w9otBkgPN6hw,KHAVA EFENDIEVA,0,1982-05-24,ru,Red Notice - Participation in illegal armed fo...,2024-03-04T17:09:51,2025-05-23T18:28:10,2024-08-08T18:27:02,0
3,NK-2Ld7pewCoLeyspMtVCMMMo,JIAN XIA,0,1977-07-13,cn,"""Red Notice - 1) Murder\n2) Manslaughter\n3) A...",2024-03-04T17:09:51,2025-05-23T18:28:10,2024-08-08T18:27:02,0
4,NK-2VDD5G22HBksrjek2CoNJo,GIENADIJ FAKTOROVICH,0,1970-06-12,il;ua,"""Red Notice - PARTICIPATION IN A CRIMINAL ORGA...",2024-03-04T17:09:51,2025-05-23T18:28:10,2024-08-08T18:27:02,0
...,...,...,...,...,...,...,...,...,...,...
6556,interpol-red-2025-6505,JULIO ENRIQUE AMAYA TURCIOS,0,1993-03-20,Unknown,Red Notice - FEMICIDIO,2025-01-31T00:27:15,2025-05-23T18:28:10,2025-01-31T00:27:15,0
6557,interpol-red-2025-6889,GUILIANG TAN,0,2001-08-10,cn,Red Notice - Criminal act of trafficking in pe...,2025-01-30T18:27:03,2025-05-23T18:28:10,2025-01-30T18:27:03,0
6558,interpol-red-2025-6891,CHEN GUOTENG,0,1971-04-24,cn,Red Notice - Criminal act of trafficking in pe...,2025-01-30T18:27:03,2025-05-23T18:28:10,2025-01-30T18:27:03,0
6559,interpol-red-2025-8298,JODY JANILLE RHAMDAS,0,1985-02-28,bz,Red Notice - Attempted Murder,2025-02-05T18:27:04,2025-05-23T18:28:10,2025-02-05T18:27:04,0
6560,interpol-red-2025-9385,MOHAMED GHARBI,0,1989-05-19,fr,Red Notice - VOL EN BANDE ORGANISEE AVEC ARME,2025-02-10T00:29:34,2025-05-23T18:28:10,2025-02-10T00:29:34,0

In [13]:
print(Interpol_data['sanctions'][1:20])

1     Red Notice - Participation in illegal armed fo...
2     Red Notice - Participation in illegal armed fo...
3     "Red Notice - 1) Murder\n2) Manslaughter\n3) A...
4     "Red Notice - PARTICIPATION IN A CRIMINAL ORGA...
5     Red Notice - murder/accomplice, manslaughter a...
6     Red Notice - assistance to terrorist activity ...
7     Red Notice - participation in illegal armed fo...
8     Red Notice - participation in an illegal armed...
9     Red Notice - participation in illegal armed fo...
10    "Red Notice - Illegal deprivation of liberty, ...
11    "Red Notice - Participation in the activity of...
12                                   Red Notice - fraud
13    Red Notice - financing of an activity of a ter...
14    Red Notice - participation in battery, causing...
15    Red Notice - participation in the activity of ...
16    Red Notice - Participation in illegal armed fo...
17    Red Notice - participation in illegal armed fo...
18    Red Notice - participation in illegal armed fo...
19    Red Notice - Murder, Endangering Public Safety...
Name: sanctions, dtype: object

In [14]:
Interpol_data['last_seen'] = pd.to_datetime(Interpol_data['last_seen'])
Interpol_data['first_seen'] = pd.to_datetime(Interpol_data['first_seen'])
Interpol_data['last_change'] = pd.to_datetime(Interpol_data['last_change'])
Interpol_data['birth_date'] = pd.to_datetime(Interpol_data['birth_date'], errors='coerce')

C:\Users\jamil\AppData\Local\Temp\ipykernel_18512\1478482744.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Interpol_data['last_seen'] = pd.to_datetime(Interpol_data['last_seen'])
C:\Users\jamil\AppData\Local\Temp\ipykernel_18512\1478482744.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Interpol_data['first_seen'] = pd.to_datetime(Interpol_data['first_seen'])
C:\Users\jamil\AppData\Local\Temp\ipykernel_18512\1478482744.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Interpol_data['last_change'] = pd.to_datetime(Interpol_data['last_change'])
C:\Users\jamil\AppData\Local\Temp\ipykernel_18512\1478482744.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Interpol_data['birth_date'] = pd.to_datetime(Interpol_data['birth_date'], errors='coerce')

In [15]:
Interpol_data

,id,name,aliases,birth_date,countries,sanctions,first_seen,last_seen,last_change,birth_date_missing
0,NK-224TRezPqwzhQZ37exWxtX,SANAVBARI NIKITENKO,0,1992-06-28,ru;tj,"""Red Notice - participation in the activity of...",2024-03-04 17:09:51,2025-05-23 18:28:10,2024-08-08 18:27:02,0
1,NK-22baaNEkbgBeZokNLmpaKd,DZHAMBULAT GALIMOV,0,1989-01-05,ru,Red Notice - Participation in illegal armed fo...,2024-03-04 17:09:51,2025-05-23 18:28:10,2024-08-08 18:27:02,0
2,NK-282timUs47w9otBkgPN6hw,KHAVA EFENDIEVA,0,1982-05-24,ru,Red Notice - Participation in illegal armed fo...,2024-03-04 17:09:51,2025-05-23 18:28:10,2024-08-08 18:27:02,0
3,NK-2Ld7pewCoLeyspMtVCMMMo,JIAN XIA,0,1977-07-13,cn,"""Red Notice - 1) Murder\n2) Manslaughter\n3) A...",2024-03-04 17:09:51,2025-05-23 18:28:10,2024-08-08 18:27:02,0
4,NK-2VDD5G22HBksrjek2CoNJo,GIENADIJ FAKTOROVICH,0,1970-06-12,il;ua,"""Red Notice - PARTICIPATION IN A CRIMINAL ORGA...",2024-03-04 17:09:51,2025-05-23 18:28:10,2024-08-08 18:27:02,0
...,...,...,...,...,...,...,...,...,...,...
6556,interpol-red-2025-6505,JULIO ENRIQUE AMAYA TURCIOS,0,1993-03-20,Unknown,Red Notice - FEMICIDIO,2025-01-31 00:27:15,2025-05-23 18:28:10,2025-01-31 00:27:15,0
6557,interpol-red-2025-6889,GUILIANG TAN,0,2001-08-10,cn,Red Notice - Criminal act of trafficking in pe...,2025-01-30 18:27:03,2025-05-23 18:28:10,2025-01-30 18:27:03,0
6558,interpol-red-2025-6891,CHEN GUOTENG,0,1971-04-24,cn,Red Notice - Criminal act of trafficking in pe...,2025-01-30 18:27:03,2025-05-23 18:28:10,2025-01-30 18:27:03,0
6559,interpol-red-2025-8298,JODY JANILLE RHAMDAS,0,1985-02-28,bz,Red Notice - Attempted Murder,2025-02-05 18:27:04,2025-05-23 18:28:10,2025-02-05 18:27:04,0
6560,interpol-red-2025-9385,MOHAMED GHARBI,0,1989-05-19,fr,Red Notice - VOL EN BANDE ORGANISEE AVEC ARME,2025-02-10 00:29:34,2025-05-23 18:28:10,2025-02-10 00:29:34,0

In [16]:
Interpol_data['aliases'].value_counts()

aliases
0                    6559
KHUSEYN AKTAMIROV       1
GUSEIN GASANOV          1
Name: count, dtype: int64

In [17]:
# drop the birth_date_missing column if present
Interpol_data.drop(columns=['birth_date_missing'], inplace=True, errors='ignore')

C:\Users\jamil\AppData\Local\Temp\ipykernel_18512\2391255567.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Interpol_data.drop(columns=['birth_date_missing'], inplace=True, errors='ignore')

In [18]:
Interpol_data.shape

(6561, 9)

In [19]:
Interpol_data.columns.tolist()

['id',
 'name',
 'aliases',
 'birth_date',
 'countries',
 'sanctions',
 'first_seen',
 'last_seen',
 'last_change']

In [20]:
# Save the processed data
Interpol_data.to_csv('Interpol_data.csv', index=False)
print("\nData Processing phase is complete. You succed in saving Data!")

Data Processing phase is complete. You succed in saving Data!